# Generated by Django 6.0.7 on 2026-07-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
